"""add users.onboarded_at

Revision ID: 3f720546888e
Revises: aa97fec2a867
Create Date: 2026-07-24 23:21:54.514882

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = '3f720546888e'
down_revision = 'aa97fec2a867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarded_at')
    # ### end Alembic commands ###
