"""agent website widget: public token, origins

Revision ID: 58c30996c187
Revises: 86afbc0dca65
Create Date: 2026-08-18 22:22:09.326743

"""
from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58c30996c187'
down_revision = '86afbc0dca65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('public_token', sa.String(length=64), nullable=True))
    # NOT NULL on a table with rows: both need a server_default to backfill.
    # Existing agents are off and embed nowhere, which is the safe default for
    # a feature that spends the platform OpenAI key.
    op.add_column(
        'agents',
        sa.Column('widget_enabled', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'agents',
        sa.Column(
            'allowed_origins',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.create_index(op.f('ix_agents_public_token'), 'agents', ['public_token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_public_token'), table_name='agents')
    op.drop_column('agents', 'allowed_origins')
    op.drop_column('agents', 'widget_enabled')
    op.drop_column('agents', 'public_token')
    # ### end Alembic commands ###
