"""chat agents: agent kind + conversation channel

Revision ID: 86afbc0dca65
Revises: 21deeaf63c2e
Create Date: 2026-08-17 22:22:34.239629

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = '86afbc0dca65'
down_revision = '21deeaf63c2e'
branch_labels = None
depends_on = None


def upgrade():
    # Both columns are NOT NULL on tables that already have rows, so they need a
    # server_default to backfill. Every existing agent is a voice agent and every
    # existing conversation is a phone call, which is exactly what the defaults
    # say — the default stays on the column afterwards so a plain INSERT that
    # predates the ORM change still works.
    op.add_column(
        'agents',
        sa.Column('kind', sa.String(length=16), nullable=False, server_default='voice'),
    )
    op.create_index(op.f('ix_agents_kind'), 'agents', ['kind'], unique=False)
    op.add_column(
        'conversations',
        sa.Column('channel', sa.String(length=16), nullable=False, server_default='voice'),
    )
    op.create_index(op.f('ix_conversations_channel'), 'conversations', ['channel'], unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_channel'), table_name='conversations')
    op.drop_column('conversations', 'channel')
    op.drop_index(op.f('ix_agents_kind'), table_name='agents')
    op.drop_column('agents', 'kind')
    # ### end Alembic commands ###
